config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'welcome#index', as: 'start'
  resources :users, only: [:new, :create]
  get '/sign_up', to: 'users#new', as: :sign_up

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  get '/log_out', to: 'sessions#destroy', as: :log_out

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User
  include Mongoid::Document
  authenticates_with_sorcery!
  validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def not_authenticated
    # Make sure that we reference the route from the main app.
    redirect_to main_app.start_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      flash[:success] = 'Welcome back!'
      redirect_to start_path
    else
      flash.now[:warning] = 'E-mail and/or password is incorrect.'
      render 'new'
    end
  end

  def destroy
    logout
    flash[:success] = 'See you!'
    redirect_to log_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
      end
    
      def create
        @user = User.new(user_params)
        if @user.save
          flash[:success] = 'Welcome!'
          login(params[:user][:email], params[:user][:password])
          redirect_to start_path
        else
          render 'new'
        end
      end
    
      private
    
      def user_params
        params.require(:user).permit(:email, :password)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcoRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EcoRails
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/new.html.haml
%h1 Registration
= form_for @user do |f|
  .form-group
    = f.label :email
    = f.email_field :email, required: true
  .form-group
    = f.label :password
    = f.password_field :password, required: true
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, required: true
  = f.submit 'Register', class: 'btn btn-primary btn-lg'

app/views/welcome/index.html.haml
%h1 Welcome#index
- if current_user != nil
  = current_user.email
  = link_to 'Logout', log_out_path
- else
  = link_to 'Sign up', sign_up_path
  = link_to 'Login', log_in_path
%p Find me in app/views/welcome/index.html.erb